#!/bin/bash

# Make sure we're running on Arch Linux.
if [ ! -f "/etc/arch-release" ]; then
    echo "Please run on Arch Linux!"
    exit 1
fi

# Make sure we're running as root.
if [ "$(id -u)" != "0" ]; then
    echo "Please run as root!"
    exit 1
fi

# Update package repositories.
echo "Updating system..."
pacman -Syy --noconfirm

# Install OpenSSH and Fail2Ban.
echo "Installing OpenSSH and Fail2Ban..."
pacman -S --noconfirm openssh fail2ban

echo "Enabling services..."
# Enable OpenSSH.
systemctl enable sshd.service

# Enable Fail2Ban.
systemctl enable fail2ban.service

echo "Configuring OpenSSH and Fail2Ban..."
# Configure OpenSSH.
# Copy the configuration file to a backup.
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

# Overwrite the configuration file.
mv ssh/sshd_config /etc/ssh/sshd_config

# Configure Fail2Ban.
# Copy the configuration file to a backup.
cp /etc/fail2ban/jail.local /etc/fail2ban/jail.local.bak

# Overwrite the configuration file.
mv fail2ban/jail.local /etc/fail2ban/jail.local

echo "Restarting services..."
# Restart OpenSSH.
systemctl restart sshd.service
# Restart Fail2Ban.
systemctl restart fail2ban.service

# Notify the user that the script has finished.
echo "Done, please make sure to port forward the SSH port on your router!"
